con.execute("""
CREATE OR REPLACE TABLE OUT AS
SELECT
    INDORG,
    NAME,
    ID1,
    ID2,
    CLASS_ID,
    PURGEDATE,
    DTL_REMARK1,
    DTL_REMARK2,
    DTL_REMARK3,
    DTL_REMARK4,
    DTL_REMARK5,
    DTL_CRT_DATE,
    DTL_CRT_TIME,
    DTL_LASTOPERATOR,
    DTL_LASTMNT_DATE,
    DTL_LASTMNT_TIME,
    CLASS_CODE,
    CLASS_DESC,
    NATURE_CODE,
    NATURE_DESC,
    DEPT_CODE,
    DEPT_DESC,
    GUIDE_CODE
FROM FULL_DESC
ORDER BY CLASS_ID, INDORG, NAME
""")
