con.execute(f"""
    CREATE OR REPLACE TABLE MSCO AS
    SELECT
        FIELDNAME,
        CAST(BC_FIELD_CODE AS VARCHAR) AS MASCO2008,
        MSCDESC
    FROM parquet_scan('{IDICFILE}')
    WHERE FIELDNAME = 'MASCO2008'
""")

con.execute(f"""
    CREATE OR REPLACE TABLE MSIC AS
    SELECT
        FIELDNAME,
        CAST(BC_FIELD_CODE AS VARCHAR) AS MSICCODE,
        MSCDESC
    FROM parquet_scan('{IDICFILE}')
    WHERE FIELDNAME = 'MSIC2008'
""")
