convert program to python with duckdb and pyarrow
duckdb for process input file and output parquet&txt
assumed all the input file ady convert to parquet can directly use it

//*------------------------------------------------------------------
//STATS#01 EXEC SAS609,OPTIONS='VERBOSE SORTLIST SORTMSG MSGLEVEL=I'
//SORTWK01  DD UNIT=SYSDA,SPACE=(CYL,(500,500))
//SORTWK02  DD UNIT=SYSDA,SPACE=(CYL,(500,500))
//SORTWK03  DD UNIT=SYSDA,SPACE=(CYL,(500,500))
//SORTWK04  DD UNIT=SYSDA,SPACE=(CYL,(500,500))
//SORTWK05  DD UNIT=SYSDA,SPACE=(CYL,(500,500))
//SORTWK06  DD UNIT=SYSDA,SPACE=(CYL,(500,500))
//SORTWK07  DD UNIT=SYSDA,SPACE=(CYL,(500,500))
//CUSTFILE DD DISP=SHR,DSN=CIS.CUST.DAILY
//CONSENT  DD DISP=SHR,DSN=REMARKS.CONSENT.ALL(+1)
//CTRLDATE  DD DISP=SHR,DSN=SRSCTRL1(0)
//ALLFILE  DD DSN=UNICARD.MAILFLAG.ALL(+1),
//            DISP=(NEW,CATLG,DELETE),
//            SPACE=(CYL,(300,300),RLSE),UNIT=SYSDA,
//            DCB=(LRECL=100,BLKSIZE=0,RECFM=FB)
//DLYFILE  DD DSN=UNICARD.MAILFLAG.DLY(+1),
//            DISP=(NEW,CATLG,DELETE),
//            SPACE=(CYL,(300,300),RLSE),UNIT=SYSDA,
//            DCB=(LRECL=100,BLKSIZE=0,RECFM=FB)
//SASLIST  DD SYSOUT=X
//SYSIN    DD *
OPTIONS NOSORTBLKMODE;
DATA SRSDATE;
      INFILE CTRLDATE;
        INPUT @001  SRSYY    4.
              @005  SRSMM    2.
              @007  SRSDD    2.;

      /* DISPLAY TODAY REPORTING DATE*/
      TODAYSAS=MDY(SRSMM,SRSDD,SRSYY);
      TODAYDATE=PUT(SRSYY,Z4.)||PUT(SRSMM,Z2.)||PUT(SRSDD,Z2.);
      CALL SYMPUT('DATE1',PUT(TODAYSAS,YYMMDD8.));
      CALL SYMPUT('DATE2',PUT(TODAYDATE,$8.));
RUN;
   PROC PRINT DATA=SRSDATE (OBS=05);TITLE 'DATE';RUN;

DATA CONSENT;
   INFILE CONSENT;
   FORMAT EFFDATETIME Z14.  EFFDATETIMEX $14.;

       INPUT @09    CUSTNO        $11. /* FROM CURRENT DB */
             @29    EFFTIMESTAMP  15.
             @44    KEYWORD       $8.
             @52    CHANNEL       $8.
             @380   CONSENT       $8.;
     EFFDATETIME = 100000000000000 - EFFTIMESTAMP ;
     EFFDATETIMEX = EFFDATETIME;
     EFFDATE = SUBSTR(EFFDATETIMEX,1,8);
     EFFTIME = SUBSTR(EFFDATETIMEX,9,6);
RUN;
   PROC SORT  DATA=CONSENT; BY CUSTNO ;RUN;
   PROC PRINT DATA=CONSENT (OBS=05);TITLE 'CONSENT';RUN;

DATA CUST;
  KEEP CUSTNO ACCTCODE ACCTNOC ALIASKEY ALIAS TAXID;
  SET CUSTFILE.CUSTDLY;
   IF ACCTCODE IN ('DP   ','LN   ','EQC  ','FSF  ') THEN DELETE;
   IF '1000000000000000' < ACCTNOC < '9999999999999999';
   IF ALIASKEY = '' AND TAXID = '' THEN DELETE;
   RUN;
   PROC SORT  DATA=CUST NODUPKEY; BY ACCTNOC;RUN;
   PROC SORT  DATA=CUST ; BY CUSTNO;RUN;
   PROC PRINT DATA=CUST (OBS=05);TITLE 'CUST';RUN;

DATA MERGE;
   MERGE CONSENT (IN=A)  CUST (IN=B); BY CUSTNO;
      IF A AND B;
   RUN;
   PROC SORT  DATA=MERGE; BY ACCTNOC;RUN;
   PROC PRINT DATA=MERGE (OBS=05);TITLE 'MERGE';RUN;

DATA ALL;
  SET MERGE;
  FILE ALLFILE;
      PUT @001  ACCTNOC        $16.
          @017  ALIASKEY       $3.
          @020  ALIAS          $12.
          @032  TAXID          $12.
          @044  CONSENT        $1.
          @045  CHANNEL        $8. ;
  RUN;

DATA DAY;
  SET MERGE;
  FILE DLYFILE;
      IF &DATE2 = EFFDATE;
      IF CHANNEL = 'UNIBATCH' THEN DELETE;
      PUT @001  ACCTNOC        $16.
          @017  ALIASKEY       $3.
          @020  ALIAS          $12.
          @032  TAXID          $12.
          @044  CONSENT        $1.
          @045  CHANNEL        $8. ;
  RETURN;
  RUN;
