# -----------------------------
# 8) TEMPALL: union all C_* tables in SAS order, include DATEUPD and OPERUPD
# -----------------------------
con.execute("""
CREATE OR REPLACE TABLE TEMPALL AS
SELECT CUSTNO, FIELDS, OLDVALUE, NEWVALUE, ACCTNOC, DATEUPD, OPERUPD FROM C_LONG
UNION ALL
SELECT CUSTNO, FIELDS, OLDVALUE, NEWVALUE, ACCTNOC, DATEUPD, OPERUPD FROM C_DOB
UNION ALL
SELECT CUSTNO, FIELDS, OLDVALUE, NEWVALUE, ACCTNOC, DATEUPD, OPERUPD FROM C_BGC
UNION ALL
SELECT CUSTNO, FIELDS, OLDVALUE, NEWVALUE, ACCTNOC, DATEUPD, OPERUPD FROM C_CORP
UNION ALL
SELECT CUSTNO, FIELDS, OLDVALUE, NEWVALUE, ACCTNOC, DATEUPD, OPERUPD FROM C_MSIC
UNION ALL
SELECT CUSTNO, FIELDS, OLDVALUE, NEWVALUE, ACCTNOC, DATEUPD, OPERUPD FROM C_CCODE
UNION ALL
SELECT CUSTNO, FIELDS, OLDVALUE, NEWVALUE, ACCTNOC, DATEUPD, OPERUPD FROM C_CTZN
UNION ALL
SELECT CUSTNO, FIELDS, OLDVALUE, NEWVALUE, ACCTNOC, DATEUPD, OPERUPD FROM C_MASCO
UNION ALL
SELECT CUSTNO, FIELDS, OLDVALUE, NEWVALUE, ACCTNOC, DATEUPD, OPERUPD FROM C_EMNAME
UNION ALL
SELECT CUSTNO, FIELDS, OLDVALUE, NEWVALUE, ACCTNOC, DATEUPD, OPERUPD FROM C_PRCTRY
UNION ALL
SELECT CUSTNO, FIELDS, OLDVALUE, NEWVALUE, ACCTNOC, DATEUPD, OPERUPD FROM C_EMSEC
UNION ALL
SELECT CUSTNO, FIELDS, OLDVALUE, NEWVALUE, ACCTNOC, DATEUPD, OPERUPD FROM C_RESD
UNION ALL
SELECT CUSTNO, FIELDS, OLDVALUE, NEWVALUE, ACCTNOC, DATEUPD, OPERUPD FROM C_EMTYP
""")

# -----------------------------
# 9) MRGCIS: merge TEMPALL with C_DATE, C_OPER, MERGE_A to bring default values
# -----------------------------
con.execute("""
CREATE OR REPLACE TABLE MRGCIS AS
SELECT
    t.CUSTNO,
    t.FIELDS,
    t.OLDVALUE,
    t.NEWVALUE,
    t.ACCTNOC,
    COALESCE(NULLIF(d.DATEUPD,''), t.DATEUPD) AS DATEUPD,
    COALESCE(NULLIF(o.OPERUPD,''), t.OPERUPD) AS OPERUPD,
    m.CUSTLASTOPER,
    m.CUSTMNTDATE,
    m.CUSTNAME
FROM TEMPALL t
LEFT JOIN C_DATE d ON t.CUSTNO = d.CUSTNO
LEFT JOIN C_OPER o ON t.CUSTNO = o.CUSTNO
LEFT JOIN MERGE_A m ON t.CUSTNO = m.CUSTNO
""")

# -----------------------------
# 10) RECORDS: apply SAS defaulting logic and exclusion list
# -----------------------------
exclusion_list = (
    'ELNBATCH','AMLBATCH','HRCBATCH','CTRBATCH','CIFLPRCE',
    'CISUPDEC','CIUPDMSX','CIUPDMS9','MAPLOANS','CRIS'
)

con.execute(f"""
CREATE OR REPLACE TABLE RECORDS AS
SELECT
    -- UPDOPER default: OPERUPD > CUSTLASTOPER
    COALESCE(NULLIF(TRIM(OPERUPD),''), NULLIF(TRIM(CUSTLASTOPER),'')) AS UPDOPER,
    CUSTNO,
    ACCTNOC,
    CUSTNAME,
    FIELDS,
    OLDVALUE,
    NEWVALUE,
    '{str(day).zfill(2)}/{str(month).zfill(2)}/{str(year)}' AS UPDDATX,
    -- UPDDATE default: DATEUPD > CUSTMNTDATE
    COALESCE(NULLIF(TRIM(DATEUPD),''), NULLIF(TRIM(CUSTMNTDATE),'')) AS UPDDATE
FROM MRGCIS
WHERE COALESCE(NULLIF(TRIM(OPERUPD),''), NULLIF(TRIM(CUSTLASTOPER),'')) NOT IN {exclusion_list}
""")

print("Processing completed. RECORDS table created.")
