con.execute(f"""
    CREATE OR REPLACE TABLE FOREX AS
    SELECT
        CURRCODE,
        CAST(FOREXRATE AS DOUBLE) AS FOREXRATE
    FROM '{host_parquet_path("SAP_PBB_FOREIGN_RATE.parquet")}'
    WHERE FOREXRATE IS NOT NULL
""")
