SELECT DISTINCT
    m.CISNO,
    m.MAIN_ENTITY_TYPE,
    m.BRANCH,
    m.CUSTNAME,
    m.BIRTHDATE,
    m.GENDER,

    -- From INDV
    ci.CISNO AS INDV_CISNO,
    ci.IDTYPE,
    ci.ID,
    ci.CUSTBRANCH,
    ci.FIRST_CREATE_DATE,
    ci.FIRST_CREATE_TIME,
    ci.FIRST_CREATE_OPER,
    ci.LAST_UPDATE_DATE,
    ci.LAST_UPDATE_TIME,
    ci.LAST_UPDATE_OPER,
    ci.LONGNAME,
    ci.ENTITYTYPE,
    ci.BNM_ASSIGNED_ID,
    ci.OLDIC,
    ci.CITIZENSHIP,
    ci.PRCOUNTRY,
    ci.RESIDENCY_STATUS,
    ci.CUSTOMER_CODE,
    ci.ADDRLINE1,
    ci.ADDRLINE2,
    ci.ADDRLINE3,
    ci.ADDRLINE4,
    ci.ADDRLINE5,
    ci.POSTCODE,
    ci.TOWN_CITY,
    ci.STATE_CODE,
    ci.COUNTRY,
    ci.ADDR_LAST_UPDATE,
    ci.ADDR_LAST_UPTIME,
    ci.PHONE_HOME,
    ci.PHONE_BUSINESS,
    ci.PHONE_FAX,
    ci.PHONE_MOBILE,
    ci.PHONE_PAC,
    ci.EMPLOYER_NAME,
    ci.MASCO2008,
    ci.MASCO2012,
    ci.EMPLOYMENT_TYPE,
    ci.EMPLOYMENT_SECTOR,
    ci.EMPLOYMENT_LAST_UPDATE,
    ci.EMPLOYMENT_LAST_UPTIME,
    ci.INCOME_AMT,
    ci.ENABLE_TAB,

    -- From CART
    ci.APPL_CODE,
    ci.APPL_NO,
    ci.PRI_SEC,
    ci.RELATIONSHIP,
    ci.AA_REF_NO,
    ci.EFF_DATE,
    ci.EFF_TIME,
    ci.LAST_MNT_DATE,
    ci.LAST_MNT_TIME,

    {year} AS year,
    {month} AS month,
    {day} AS day
FROM main_indv m
INNER JOIN custinfo_indv ci
    ON m.CISNO = ci.CISNO
ORDER BY m.CISNO

SELECT DISTINCT
    m.CISNO,
    m.MAIN_ENTITY_TYPE,
    m.BRANCH,
    m.CUSTNAME,
    m.BIRTHDATE,
    m.GENDER,

    -- From ORG
    co.CISNO AS ORG_CISNO,
    co.IDTYPE,
    co.ID,
    co.BRANCH AS ORG_BRANCH,
    co.FIRST_CREATE_DATE,
    co.FIRST_CREATE_TIME,
    co.FIRST_CREATE_OPER,
    co.LAST_UPDATE_DATE,
    co.LAST_UPDATE_TIME,
    co.LAST_UPDATE_OPER,
    co.LONG_NAME,
    co.ENTITY_TYPE,
    co.BNM_ASSIGNED_ID,
    co.REGISTRATION_DATE,
    co.MSIC2008,
    co.RESIDENCY_STATUS,
    co.CORPORATE_STATUS,
    co.CUSTOMER_CODE,
    co.CITIZENSHIP,
    co.ADDR_LINE_1,
    co.ADDR_LINE_2,
    co.ADDR_LINE_3,
    co.ADDR_LINE_4,
    co.ADDR_LINE_5,
    co.POSTCODE,
    co.TOWN_CITY,
    co.STATE_CODE,
    co.COUNTRY,
    co.ADDR_LAST_UPDATE,
    co.ADDR_LAST_UPTIME,
    co.PHONE_PRIMARY,
    co.PHONE_SECONDARY,
    co.PHONE_FAX,
    co.PHONE_MOBILE,
    co.PHONE_PAC,
    co.ENABLE_TAB,

    -- From CART
    co.APPL_CODE,
    co.APPL_NO,
    co.PRI_SEC,
    co.RELATIONSHIP,
    co.AA_REF_NO,
    co.EFF_DATE,
    co.EFF_TIME,
    co.LAST_MNT_DATE,
    co.LAST_MNT_TIME,

    {year} AS year,
    {month} AS month,
    {day} AS day
FROM main_org m
INNER JOIN custinfo_org co
    ON m.CISNO = co.CISNO
ORDER BY m.CISNO
