Python Challenges

Challenge 1: Finding Dataset

Identify and understand the field layout of each dataset.

Some jobs are not scheduled in Site 5, which requires additional time to create UAT data.

Challenge 2: Creating New Functions

New functions need to be developed when facing technical issues or new requirements.

For example, functions such as reading Hive Parquet files, calling Parquet paths, or accessing Parquet files generated by other teams.

Challenge 3: Setup Challenges

The server setup and Python project development are progressing concurrently.

The Python migration project is still undergoing continuous setup improvements, such as:

Configuring trigger files to initiate Python workflows.

Organizing folder structures with clear naming conventions.

Managing housekeeping tasks, as limited server storage often causes issues.

Challenge 4: Obtaining Parquet Files from Other Teams

Each team has different starting points and processing methods, leading to variations in the required Parquet files.

In some cases, Parquet files can be converted on our side. However, if the source data is in a different format (e.g., SAS datasets or non-fixed binary formats), we need to wait for other teams to provide the required files.
