CREATE OR REPLACE TABLE TEMPALL AS
SELECT CUSTNO, FIELDS, OLDVALUE, NEWVALUE, ACCTNOC FROM C_LONG
UNION ALL
SELECT CUSTNO, FIELDS, OLDVALUE, NEWVALUE, ACCTNOC FROM C_DOB
UNION ALL
SELECT CUSTNO, FIELDS, OLDVALUE, NEWVALUE, ACCTNOC FROM C_BGC
UNION ALL
SELECT CUSTNO, FIELDS, OLDVALUE, NEWVALUE, ACCTNOC FROM C_CORP
UNION ALL
SELECT CUSTNO, FIELDS, OLDVALUE, NEWVALUE, ACCTNOC FROM C_MSIC
UNION ALL
SELECT CUSTNO, FIELDS, OLDVALUE, NEWVALUE, ACCTNOC FROM C_CCODE
UNION ALL
SELECT CUSTNO, FIELDS, OLDVALUE, NEWVALUE, ACCTNOC FROM C_CTZN
UNION ALL
SELECT CUSTNO, FIELDS, OLDVALUE, NEWVALUE, ACCTNOC FROM C_MASCO
UNION ALL
SELECT CUSTNO, FIELDS, OLDVALUE, NEWVALUE, ACCTNOC FROM C_EMNAME
UNION ALL
SELECT CUSTNO, FIELDS, OLDVALUE, NEWVALUE, ACCTNOC FROM C_PRCTRY
UNION ALL
SELECT CUSTNO, FIELDS, OLDVALUE, NEWVALUE, ACCTNOC FROM C_EMSEC
UNION ALL
SELECT CUSTNO, FIELDS, OLDVALUE, NEWVALUE, ACCTNOC FROM C_RESD
UNION ALL
SELECT CUSTNO, FIELDS, OLDVALUE, NEWVALUE, ACCTNOC FROM C_EMTYP
