CREATE OR REPLACE TABLE DEPOSIT AS
SELECT
    CAST(BANKNO AS BIGINT) AS BANKNO,
    CAST(REPTNO AS BIGINT) AS REPTNO,
    CAST(FMTCODE AS BIGINT) AS FMTCODE,
    CAST(BRANCHNO AS BIGINT) AS BRANCHNO,
    CAST(ACCTNO AS BIGINT) AS ACCTNO,
    ACCTX,
    CLSEDATE,
    OPENDATE,
    CAST(HOLDAMT AS DOUBLE) AS HOLDAMT,
    CAST(LEDGERBAL AS DOUBLE) AS LEDGERBAL,
    ODLIMIT,
    CURRCODE,
    OPENIND,
    DORMIND,
    COSTCTR,
    POSTIND,
    BANKINDC,
    FOREXAMT,
    ACCTSTATUS,
    OPENDD,
    OPENMM,
    OPENYY,
    CLSEDD,
    CLSEMM,
    CLSEYY
FROM DPMYR

UNION ALL

SELECT
    CAST(BANKNO AS BIGINT) AS BANKNO,
    CAST(REPTNO AS BIGINT) AS REPTNO,
    CAST(FMTCODE AS BIGINT) AS FMTCODE,
    CAST(BRANCHNO AS BIGINT) AS BRANCHNO,
    CAST(ACCTNO AS BIGINT) AS ACCTNO,
    ACCTX,
    CLSEDATE,
    OPENDATE,
    CAST(HOLDAMT AS DOUBLE) AS HOLDAMT,
    CAST(LEDGERBAL AS DOUBLE) AS LEDGERBAL,
    ODLIMIT,
    CURRCODE,
    OPENIND,
    DORMIND,
    COSTCTR,
    POSTIND,
    BANKINDC,
    FOREXAMT,
    ACCTSTATUS,
    OPENDD,
    OPENMM,
    OPENYY,
    CLSEDD,
    CLSEMM,
    CLSEYY
FROM FOREXMRG;


CREATE OR REPLACE TABLE DEPOSIT2 AS
SELECT
    d.*,
    f.ACCTSTATUS AS FRZ_STATUS,
    f.DATECLSE
FROM DEPOSIT d
LEFT JOIN FRZ f
ON CAST(d.ACCTNO AS VARCHAR) = f.ACCTNO;
