con.execute("""
    CREATE TABLE MERGED AS
    SELECT
        CIS.CUSTBRCH,
        CIS.CUSTNO,
        CIS.CUSTNAME,
        CIS.RACE,
        CIS.CITIZENSHIP,
        CIS.INDORG,
        CIS.PRISEC,
        CASE 
            WHEN CIS.PRISEC = 901 THEN 'P'
            WHEN CIS.PRISEC = 902 THEN 'S'
            ELSE '' 
        END AS PRIMSEC,
        CIS.CUSTLASTDATECC,
        CIS.CUSTLASTDATEYY,
        CIS.CUSTLASTDATEMM,
        CIS.CUSTLASTDATEDD,
        CIS.ALIASKEY,
        CIS.ALIAS,
        HRCCUST.HRCCODES,
        CIS.ACCTCODE,
        CIS.ACCTNO
    FROM CIS
    JOIN HRCCUST
    ON CIS.CUSTNO = HRCCUST.CUSTNO
""")
